"""
Module 3 — Rule-Based Threat Detection

Pure, explainable rules — no machine learning. Each rule function takes the
normalized events DataFrame and returns a list of alert dicts. Alerts are
generated by grouping events within a sliding time window per source IP,
which keeps the logic simple enough to explain line-by-line in a viva.
"""

import os
import sys
import uuid

import pandas as pd

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import settings


def _new_alert_id():
    return "ALT-" + uuid.uuid4().hex[:8].upper()


def _windowed_groups(df, window_minutes):
    """Yield (ip, sub_df) groups where sub_df events fall within a rolling
    window_minutes of each other, per source IP. Simple greedy windowing:
    sort by time, start a new window whenever the gap since the window's
    first event exceeds window_minutes.
    """
    if df.empty:
        return
    for ip, group in df.groupby("source_ip"):
        group = group.sort_values("timestamp")
        window_start = None
        bucket = []
        for _, row in group.iterrows():
            if window_start is None:
                window_start = row["timestamp"]
                bucket = [row]
                continue
            if (row["timestamp"] - window_start).total_seconds() <= window_minutes * 60:
                bucket.append(row)
            else:
                if bucket:
                    yield ip, pd.DataFrame(bucket)
                window_start = row["timestamp"]
                bucket = [row]
        if bucket:
            yield ip, pd.DataFrame(bucket)


def rule_brute_force(df):
    """Rule 1: 5+ failed SSH logins from the same IP within 5 minutes."""
    alerts = []
    failed = df[(df["event_type"].isin(["failed_login", "invalid_user_attempt"]))]
    for ip, bucket in _windowed_groups(failed, settings.BRUTE_FORCE_WINDOW_MINUTES):
        if len(bucket) >= settings.BRUTE_FORCE_ATTEMPTS:
            alerts.append({
                "alert_id": _new_alert_id(),
                "timestamp": bucket["timestamp"].max(),
                "threat_type": "Brute Force",
                "source_ip": ip,
                "severity": settings.RULE_SEVERITY["Brute Force Detection"],
                "description": (
                    f"{len(bucket)} failed SSH login attempts from {ip} within "
                    f"{settings.BRUTE_FORCE_WINDOW_MINUTES} minutes."
                ),
                "detection_rule": "Brute Force Detection",
                "related_event_count": len(bucket),
                "status": "New",
            })
    return alerts


def rule_suspicious_login(df):
    """Rule 2: failed logins against multiple distinct usernames, same IP."""
    alerts = []
    failed = df[(df["event_type"].isin(["failed_login", "invalid_user_attempt"]))]
    for ip, bucket in _windowed_groups(failed, settings.MULTI_USER_WINDOW_MINUTES):
        distinct_users = bucket["username"].nunique()
        if len(bucket) >= settings.MULTI_USER_ATTEMPTS and distinct_users >= settings.MULTI_USER_DISTINCT_USERNAMES:
            alerts.append({
                "alert_id": _new_alert_id(),
                "timestamp": bucket["timestamp"].max(),
                "threat_type": "Suspicious Login",
                "source_ip": ip,
                "severity": settings.RULE_SEVERITY["Suspicious Login Activity"],
                "description": (
                    f"{len(bucket)} failed login attempts against {distinct_users} distinct "
                    f"usernames from {ip} — possible username enumeration."
                ),
                "detection_rule": "Suspicious Login Activity",
                "related_event_count": len(bucket),
                "status": "New",
            })
    return alerts


def rule_suspicious_web_request(df):
    """Rule 3: repeated requests to suspicious/scanning paths, same IP."""
    alerts = []
    web = df[df["service"] == "apache"].copy()
    if web.empty:
        return alerts
    web["is_suspicious"] = web["request"].fillna("").apply(
        lambda r: any(p in r for p in settings.SUSPICIOUS_PATHS)
    )
    suspicious = web[web["is_suspicious"]]
    for ip, bucket in _windowed_groups(suspicious, settings.SUSPICIOUS_PATH_WINDOW_MINUTES):
        if len(bucket) >= settings.SUSPICIOUS_PATH_HITS:
            alerts.append({
                "alert_id": _new_alert_id(),
                "timestamp": bucket["timestamp"].max(),
                "threat_type": "Suspicious Web Request",
                "source_ip": ip,
                "severity": settings.RULE_SEVERITY["Suspicious Web Request"],
                "description": (
                    f"{len(bucket)} requests to suspicious/scanning paths from {ip} "
                    f"within {settings.SUSPICIOUS_PATH_WINDOW_MINUTES} minutes."
                ),
                "detection_rule": "Suspicious Web Request",
                "related_event_count": len(bucket),
                "status": "New",
            })
    return alerts


def rule_excessive_404(df):
    """Rule 4: unusually high 404 responses from the same IP, short window."""
    alerts = []
    not_found = df[(df["service"] == "apache") & (df["status"] == "not_found")]
    for ip, bucket in _windowed_groups(not_found, settings.EXCESSIVE_404_WINDOW_MINUTES):
        if len(bucket) >= settings.EXCESSIVE_404_COUNT:
            alerts.append({
                "alert_id": _new_alert_id(),
                "timestamp": bucket["timestamp"].max(),
                "threat_type": "Excessive 404",
                "source_ip": ip,
                "severity": settings.RULE_SEVERITY["Excessive 404 Requests"],
                "description": (
                    f"{len(bucket)} HTTP 404 responses to {ip} within "
                    f"{settings.EXCESSIVE_404_WINDOW_MINUTES} minutes — possible endpoint scanning."
                ),
                "detection_rule": "Excessive 404 Requests",
                "related_event_count": len(bucket),
                "status": "New",
            })
    return alerts


def rule_restricted_resource_access(df):
    """Rule 5: repeated requests to explicitly restricted paths."""
    alerts = []
    web = df[df["service"] == "apache"].copy()
    if web.empty:
        return alerts
    web["hits_restricted"] = web["request"].fillna("").apply(
        lambda r: any(p in r for p in settings.RESTRICTED_PATHS)
    )
    restricted = web[web["hits_restricted"]]
    for ip, bucket in _windowed_groups(restricted, settings.RESTRICTED_WINDOW_MINUTES):
        if len(bucket) >= settings.RESTRICTED_HITS:
            alerts.append({
                "alert_id": _new_alert_id(),
                "timestamp": bucket["timestamp"].max(),
                "threat_type": "Restricted Resource Access",
                "source_ip": ip,
                "severity": settings.RULE_SEVERITY["Restricted Resource Access"],
                "description": (
                    f"{len(bucket)} requests to restricted administrative paths "
                    f"(e.g. /admin, /login, /config) from {ip}."
                ),
                "detection_rule": "Restricted Resource Access",
                "related_event_count": len(bucket),
                "status": "New",
            })
    return alerts


ALL_RULES = [
    rule_brute_force,
    rule_suspicious_login,
    rule_suspicious_web_request,
    rule_excessive_404,
    rule_restricted_resource_access,
]
